// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataflow.proto

/*
Package dataflow is a generated protocol buffer package.

It is generated from these files:
	dataflow.proto

It has these top-level messages:
	Schedule
	Policy
	GetPolicyRequest
	GetPolicyResponse
	ListPolicyRequest
	ListPolicyResponse
	CreatePolicyRequest
	CreatePolicyResponse
	UpdatePolicyRequest
	UpdatePolicyResponse
	DeletePolicyRequest
	DeletePolicyResponse
	KV
	Filter
	Connector
	Plan
	CreatePlanRequest
	CreatePlanResponse
	GetPlanRequest
	GetPlanResponse
	ListPlanRequest
	ListPlanResponse
	UpdatePlanRequest
	UpdatePlanResponse
	DeletePlanRequest
	DeletePlanResponse
	RunPlanRequest
	RunPlanResponse
	Job
	GetJobRequest
	GetJobResponse
	ListJobRequest
	ListJobResponse
*/
package dataflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Schedule struct {
	Type             string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Days             []string `protobuf:"bytes,2,rep,name=days" json:"days,omitempty"`
	TimePoint        string   `protobuf:"bytes,3,opt,name=time_point,json=timePoint" json:"time_point,omitempty"`
	TiggerProperties string   `protobuf:"bytes,4,opt,name=tigger_properties,json=tiggerProperties" json:"tigger_properties,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Schedule) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Schedule) GetDays() []string {
	if m != nil {
		return m.Days
	}
	return nil
}

func (m *Schedule) GetTimePoint() string {
	if m != nil {
		return m.TimePoint
	}
	return ""
}

func (m *Schedule) GetTiggerProperties() string {
	if m != nil {
		return m.TiggerProperties
	}
	return ""
}

type Policy struct {
	Id          string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tenant      string    `protobuf:"bytes,3,opt,name=tenant" json:"tenant,omitempty"`
	Description string    `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Schedule    *Schedule `protobuf:"bytes,5,opt,name=schedule" json:"schedule,omitempty"`
}

func (m *Policy) Reset()                    { *m = Policy{} }
func (m *Policy) String() string            { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()               {}
func (*Policy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Policy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Policy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Policy) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Policy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Policy) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type GetPolicyRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetPolicyRequest) Reset()                    { *m = GetPolicyRequest{} }
func (m *GetPolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPolicyRequest) ProtoMessage()               {}
func (*GetPolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetPolicyRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *GetPolicyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPolicyResponse struct {
	Err string  `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Pol *Policy `protobuf:"bytes,2,opt,name=pol" json:"pol,omitempty"`
}

func (m *GetPolicyResponse) Reset()                    { *m = GetPolicyResponse{} }
func (m *GetPolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPolicyResponse) ProtoMessage()               {}
func (*GetPolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetPolicyResponse) GetPol() *Policy {
	if m != nil {
		return m.Pol
	}
	return nil
}

type ListPolicyRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *ListPolicyRequest) Reset()                    { *m = ListPolicyRequest{} }
func (m *ListPolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPolicyRequest) ProtoMessage()               {}
func (*ListPolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListPolicyRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type ListPolicyResponse struct {
	Err  string    `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Pols []*Policy `protobuf:"bytes,2,rep,name=pols" json:"pols,omitempty"`
}

func (m *ListPolicyResponse) Reset()                    { *m = ListPolicyResponse{} }
func (m *ListPolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPolicyResponse) ProtoMessage()               {}
func (*ListPolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListPolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *ListPolicyResponse) GetPols() []*Policy {
	if m != nil {
		return m.Pols
	}
	return nil
}

type CreatePolicyRequest struct {
	Context string  `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Pol     *Policy `protobuf:"bytes,2,opt,name=pol" json:"pol,omitempty"`
}

func (m *CreatePolicyRequest) Reset()                    { *m = CreatePolicyRequest{} }
func (m *CreatePolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePolicyRequest) ProtoMessage()               {}
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreatePolicyRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *CreatePolicyRequest) GetPol() *Policy {
	if m != nil {
		return m.Pol
	}
	return nil
}

type CreatePolicyResponse struct {
	Err   string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PolId string `protobuf:"bytes,2,opt,name=polId" json:"polId,omitempty"`
}

func (m *CreatePolicyResponse) Reset()                    { *m = CreatePolicyResponse{} }
func (m *CreatePolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePolicyResponse) ProtoMessage()               {}
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreatePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreatePolicyResponse) GetPolId() string {
	if m != nil {
		return m.PolId
	}
	return ""
}

type UpdatePolicyRequest struct {
	Context string  `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Pol     *Policy `protobuf:"bytes,2,opt,name=pol" json:"pol,omitempty"`
}

func (m *UpdatePolicyRequest) Reset()                    { *m = UpdatePolicyRequest{} }
func (m *UpdatePolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePolicyRequest) ProtoMessage()               {}
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdatePolicyRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *UpdatePolicyRequest) GetPol() *Policy {
	if m != nil {
		return m.Pol
	}
	return nil
}

type UpdatePolicyResponse struct {
	Err   string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PolId string `protobuf:"bytes,2,opt,name=polId" json:"polId,omitempty"`
}

func (m *UpdatePolicyResponse) Reset()                    { *m = UpdatePolicyResponse{} }
func (m *UpdatePolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePolicyResponse) ProtoMessage()               {}
func (*UpdatePolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdatePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *UpdatePolicyResponse) GetPolId() string {
	if m != nil {
		return m.PolId
	}
	return ""
}

type DeletePolicyRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeletePolicyRequest) Reset()                    { *m = DeletePolicyRequest{} }
func (m *DeletePolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePolicyRequest) ProtoMessage()               {}
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeletePolicyRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *DeletePolicyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePolicyResponse struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeletePolicyResponse) Reset()                    { *m = DeletePolicyResponse{} }
func (m *DeletePolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*DeletePolicyResponse) ProtoMessage()               {}
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeletePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type KV struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Filter struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Tag    []*KV  `protobuf:"bytes,2,rep,name=tag" json:"tag,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Filter) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Filter) GetTag() []*KV {
	if m != nil {
		return m.Tag
	}
	return nil
}

type Connector struct {
	StorType   string `protobuf:"bytes,1,opt,name=storType" json:"storType,omitempty"`
	BucketName string `protobuf:"bytes,2,opt,name=bucketName" json:"bucketName,omitempty"`
	ConnConfig []*KV  `protobuf:"bytes,3,rep,name=connConfig" json:"connConfig,omitempty"`
}

func (m *Connector) Reset()                    { *m = Connector{} }
func (m *Connector) String() string            { return proto.CompactTextString(m) }
func (*Connector) ProtoMessage()               {}
func (*Connector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Connector) GetStorType() string {
	if m != nil {
		return m.StorType
	}
	return ""
}

func (m *Connector) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *Connector) GetConnConfig() []*KV {
	if m != nil {
		return m.ConnConfig
	}
	return nil
}

type Plan struct {
	Id           string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name         string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  string     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Type         string     `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	PolicyId     string     `protobuf:"bytes,5,opt,name=policyId" json:"policyId,omitempty"`
	PolicyName   string     `protobuf:"bytes,6,opt,name=policyName" json:"policyName,omitempty"`
	SourceConn   *Connector `protobuf:"bytes,7,opt,name=sourceConn" json:"sourceConn,omitempty"`
	DestConn     *Connector `protobuf:"bytes,8,opt,name=destConn" json:"destConn,omitempty"`
	Filt         *Filter    `protobuf:"bytes,9,opt,name=filt" json:"filt,omitempty"`
	OverWrite    bool       `protobuf:"varint,10,opt,name=overWrite" json:"overWrite,omitempty"`
	RemainSource bool       `protobuf:"varint,11,opt,name=remainSource" json:"remainSource,omitempty"`
	Tenant       string     `protobuf:"bytes,12,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *Plan) Reset()                    { *m = Plan{} }
func (m *Plan) String() string            { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()               {}
func (*Plan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Plan) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Plan) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *Plan) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *Plan) GetSourceConn() *Connector {
	if m != nil {
		return m.SourceConn
	}
	return nil
}

func (m *Plan) GetDestConn() *Connector {
	if m != nil {
		return m.DestConn
	}
	return nil
}

func (m *Plan) GetFilt() *Filter {
	if m != nil {
		return m.Filt
	}
	return nil
}

func (m *Plan) GetOverWrite() bool {
	if m != nil {
		return m.OverWrite
	}
	return false
}

func (m *Plan) GetRemainSource() bool {
	if m != nil {
		return m.RemainSource
	}
	return false
}

func (m *Plan) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type CreatePlanRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Plan    *Plan  `protobuf:"bytes,2,opt,name=plan" json:"plan,omitempty"`
}

func (m *CreatePlanRequest) Reset()                    { *m = CreatePlanRequest{} }
func (m *CreatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePlanRequest) ProtoMessage()               {}
func (*CreatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CreatePlanRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *CreatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type CreatePlanResponse struct {
	Err    string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PlanId string `protobuf:"bytes,2,opt,name=planId" json:"planId,omitempty"`
}

func (m *CreatePlanResponse) Reset()                    { *m = CreatePlanResponse{} }
func (m *CreatePlanResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePlanResponse) ProtoMessage()               {}
func (*CreatePlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreatePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreatePlanResponse) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type GetPlanRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetPlanRequest) Reset()                    { *m = GetPlanRequest{} }
func (m *GetPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPlanRequest) ProtoMessage()               {}
func (*GetPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetPlanRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *GetPlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPlanResponse struct {
	Err  string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Plan *Plan  `protobuf:"bytes,2,opt,name=plan" json:"plan,omitempty"`
}

func (m *GetPlanResponse) Reset()                    { *m = GetPlanResponse{} }
func (m *GetPlanResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPlanResponse) ProtoMessage()               {}
func (*GetPlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetPlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetPlanResponse) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type ListPlanRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *ListPlanRequest) Reset()                    { *m = ListPlanRequest{} }
func (m *ListPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPlanRequest) ProtoMessage()               {}
func (*ListPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ListPlanRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type ListPlanResponse struct {
	Err   string  `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Plans []*Plan `protobuf:"bytes,2,rep,name=plans" json:"plans,omitempty"`
}

func (m *ListPlanResponse) Reset()                    { *m = ListPlanResponse{} }
func (m *ListPlanResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPlanResponse) ProtoMessage()               {}
func (*ListPlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ListPlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *ListPlanResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

type UpdatePlanRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Plan    *Plan  `protobuf:"bytes,2,opt,name=plan" json:"plan,omitempty"`
}

func (m *UpdatePlanRequest) Reset()                    { *m = UpdatePlanRequest{} }
func (m *UpdatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlanRequest) ProtoMessage()               {}
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *UpdatePlanRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *UpdatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type UpdatePlanResponse struct {
	Err    string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PlanId string `protobuf:"bytes,2,opt,name=planId" json:"planId,omitempty"`
}

func (m *UpdatePlanResponse) Reset()                    { *m = UpdatePlanResponse{} }
func (m *UpdatePlanResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlanResponse) ProtoMessage()               {}
func (*UpdatePlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *UpdatePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *UpdatePlanResponse) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type DeletePlanRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeletePlanRequest) Reset()                    { *m = DeletePlanRequest{} }
func (m *DeletePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanRequest) ProtoMessage()               {}
func (*DeletePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *DeletePlanRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *DeletePlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePlanResponse struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeletePlanResponse) Reset()                    { *m = DeletePlanResponse{} }
func (m *DeletePlanResponse) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanResponse) ProtoMessage()               {}
func (*DeletePlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *DeletePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type RunPlanRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *RunPlanRequest) Reset()                    { *m = RunPlanRequest{} }
func (m *RunPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*RunPlanRequest) ProtoMessage()               {}
func (*RunPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *RunPlanRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *RunPlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RunPlanResponse struct {
	Err   string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	JobId string `protobuf:"bytes,2,opt,name=jobId" json:"jobId,omitempty"`
}

func (m *RunPlanResponse) Reset()                    { *m = RunPlanResponse{} }
func (m *RunPlanResponse) String() string            { return proto.CompactTextString(m) }
func (*RunPlanResponse) ProtoMessage()               {}
func (*RunPlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *RunPlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *RunPlanResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type Job struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type           string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	PlanName       string `protobuf:"bytes,3,opt,name=planName" json:"planName,omitempty"`
	PlanId         string `protobuf:"bytes,4,opt,name=planId" json:"planId,omitempty"`
	Description    string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	SourceLocation string `protobuf:"bytes,6,opt,name=sourceLocation" json:"sourceLocation,omitempty"`
	DestLocation   string `protobuf:"bytes,7,opt,name=destLocation" json:"destLocation,omitempty"`
	CreateTime     int64  `protobuf:"varint,8,opt,name=createTime" json:"createTime,omitempty"`
	StartTime      int64  `protobuf:"varint,9,opt,name=startTime" json:"startTime,omitempty"`
	EndTime        int64  `protobuf:"varint,10,opt,name=endTime" json:"endTime,omitempty"`
	OverWrite      bool   `protobuf:"varint,11,opt,name=overWrite" json:"overWrite,omitempty"`
	RemainSource   bool   `protobuf:"varint,12,opt,name=remainSource" json:"remainSource,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Job) GetPlanName() string {
	if m != nil {
		return m.PlanName
	}
	return ""
}

func (m *Job) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetSourceLocation() string {
	if m != nil {
		return m.SourceLocation
	}
	return ""
}

func (m *Job) GetDestLocation() string {
	if m != nil {
		return m.DestLocation
	}
	return ""
}

func (m *Job) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Job) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Job) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Job) GetOverWrite() bool {
	if m != nil {
		return m.OverWrite
	}
	return false
}

func (m *Job) GetRemainSource() bool {
	if m != nil {
		return m.RemainSource
	}
	return false
}

type GetJobRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetJobRequest) Reset()                    { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string            { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()               {}
func (*GetJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *GetJobRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *GetJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetJobResponse struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Job *Job   `protobuf:"bytes,2,opt,name=job" json:"job,omitempty"`
}

func (m *GetJobResponse) Reset()                    { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string            { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()               {}
func (*GetJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *GetJobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetJobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type ListJobRequest struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *ListJobRequest) Reset()                    { *m = ListJobRequest{} }
func (m *ListJobRequest) String() string            { return proto.CompactTextString(m) }
func (*ListJobRequest) ProtoMessage()               {}
func (*ListJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ListJobRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type ListJobResponse struct {
	Err  string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Jobs []*Job `protobuf:"bytes,2,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *ListJobResponse) Reset()                    { *m = ListJobResponse{} }
func (m *ListJobResponse) String() string            { return proto.CompactTextString(m) }
func (*ListJobResponse) ProtoMessage()               {}
func (*ListJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *ListJobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *ListJobResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Schedule)(nil), "Schedule")
	proto.RegisterType((*Policy)(nil), "Policy")
	proto.RegisterType((*GetPolicyRequest)(nil), "GetPolicyRequest")
	proto.RegisterType((*GetPolicyResponse)(nil), "GetPolicyResponse")
	proto.RegisterType((*ListPolicyRequest)(nil), "ListPolicyRequest")
	proto.RegisterType((*ListPolicyResponse)(nil), "ListPolicyResponse")
	proto.RegisterType((*CreatePolicyRequest)(nil), "CreatePolicyRequest")
	proto.RegisterType((*CreatePolicyResponse)(nil), "CreatePolicyResponse")
	proto.RegisterType((*UpdatePolicyRequest)(nil), "UpdatePolicyRequest")
	proto.RegisterType((*UpdatePolicyResponse)(nil), "UpdatePolicyResponse")
	proto.RegisterType((*DeletePolicyRequest)(nil), "DeletePolicyRequest")
	proto.RegisterType((*DeletePolicyResponse)(nil), "DeletePolicyResponse")
	proto.RegisterType((*KV)(nil), "KV")
	proto.RegisterType((*Filter)(nil), "Filter")
	proto.RegisterType((*Connector)(nil), "Connector")
	proto.RegisterType((*Plan)(nil), "Plan")
	proto.RegisterType((*CreatePlanRequest)(nil), "CreatePlanRequest")
	proto.RegisterType((*CreatePlanResponse)(nil), "CreatePlanResponse")
	proto.RegisterType((*GetPlanRequest)(nil), "GetPlanRequest")
	proto.RegisterType((*GetPlanResponse)(nil), "GetPlanResponse")
	proto.RegisterType((*ListPlanRequest)(nil), "ListPlanRequest")
	proto.RegisterType((*ListPlanResponse)(nil), "ListPlanResponse")
	proto.RegisterType((*UpdatePlanRequest)(nil), "UpdatePlanRequest")
	proto.RegisterType((*UpdatePlanResponse)(nil), "UpdatePlanResponse")
	proto.RegisterType((*DeletePlanRequest)(nil), "DeletePlanRequest")
	proto.RegisterType((*DeletePlanResponse)(nil), "DeletePlanResponse")
	proto.RegisterType((*RunPlanRequest)(nil), "RunPlanRequest")
	proto.RegisterType((*RunPlanResponse)(nil), "RunPlanResponse")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*GetJobRequest)(nil), "GetJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "GetJobResponse")
	proto.RegisterType((*ListJobRequest)(nil), "ListJobRequest")
	proto.RegisterType((*ListJobResponse)(nil), "ListJobResponse")
}

func init() { proto.RegisterFile("dataflow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x96, 0x45, 0x49, 0x96, 0xc6, 0xfe, 0x75, 0x18, 0xc9, 0x3f, 0x58, 0xf6, 0x00, 0x63, 0x8b,
	0x1a, 0x46, 0xdc, 0x2e, 0x50, 0xb7, 0x40, 0x90, 0xa0, 0x76, 0x5b, 0x38, 0x48, 0x1a, 0x27, 0x28,
	0x0c, 0x25, 0x4d, 0x2f, 0x03, 0x4a, 0x5a, 0xbb, 0xb4, 0x69, 0x2e, 0x4b, 0xae, 0x92, 0xe8, 0xa6,
	0x6f, 0xd0, 0x87, 0xeb, 0x43, 0x14, 0x7d, 0x8d, 0x62, 0x0f, 0x3c, 0x4b, 0xaa, 0x1c, 0xe4, 0x6e,
	0xe7, 0xdb, 0x99, 0x9d, 0xd9, 0xe1, 0x7e, 0x9f, 0x46, 0xd0, 0x9d, 0xb9, 0xc2, 0xbd, 0xf4, 0xf9,
	0x5b, 0x1a, 0x46, 0x5c, 0x70, 0xf2, 0x07, 0xb4, 0x5f, 0x4c, 0x7f, 0x63, 0xb3, 0xb9, 0xcf, 0x10,
	0xa1, 0x21, 0x16, 0x21, 0xb3, 0xb7, 0xf6, 0xb7, 0x0e, 0x3b, 0x63, 0xb5, 0x96, 0xd8, 0xcc, 0x5d,
	0xc4, 0x76, 0x7d, 0xdf, 0x92, 0x98, 0x5c, 0xe3, 0xa7, 0x00, 0xc2, 0xbb, 0x65, 0xaf, 0x43, 0xee,
	0x05, 0xc2, 0xb6, 0x94, 0x77, 0x47, 0x22, 0x17, 0x12, 0xc0, 0x23, 0x18, 0x08, 0xef, 0xea, 0x8a,
	0x45, 0xaf, 0xc3, 0x88, 0x87, 0x2c, 0x12, 0x1e, 0x8b, 0xed, 0x86, 0xf2, 0xea, 0xeb, 0x8d, 0x8b,
	0x14, 0x27, 0x7f, 0x6e, 0x41, 0xeb, 0x82, 0xfb, 0xde, 0x74, 0x81, 0x5d, 0xa8, 0x7b, 0x33, 0x93,
	0xbc, 0xee, 0xcd, 0x64, 0xea, 0xc0, 0xbd, 0x65, 0x76, 0x5d, 0x97, 0x23, 0xd7, 0xf8, 0x7f, 0x68,
	0x09, 0x16, 0xb8, 0x69, 0x5a, 0x63, 0xe1, 0x3e, 0xec, 0xcc, 0x58, 0x3c, 0x8d, 0xbc, 0x50, 0x78,
	0x3c, 0x30, 0xd9, 0xf2, 0x10, 0x7e, 0x01, 0xed, 0xd8, 0x5c, 0xd4, 0x6e, 0xee, 0x6f, 0x1d, 0xee,
	0x1c, 0x77, 0x68, 0x72, 0xf3, 0x71, 0xba, 0x45, 0xbe, 0x83, 0xfe, 0x13, 0x26, 0x74, 0x45, 0x63,
	0xf6, 0xfb, 0x9c, 0xc5, 0x02, 0x6d, 0xd8, 0x9e, 0xf2, 0x40, 0xb0, 0x77, 0xc2, 0x54, 0x97, 0x98,
	0xa6, 0xe4, 0x7a, 0x52, 0x32, 0xf9, 0x01, 0x06, 0xb9, 0xe8, 0x38, 0xe4, 0x41, 0xcc, 0xb0, 0x0f,
	0x16, 0x8b, 0x22, 0x13, 0x2a, 0x97, 0xf8, 0x11, 0x58, 0x21, 0xf7, 0x55, 0xdc, 0xce, 0xf1, 0x36,
	0x35, 0xfe, 0x12, 0x23, 0x5f, 0xc1, 0xe0, 0xb9, 0x17, 0x6f, 0x5a, 0x00, 0x39, 0x03, 0xcc, 0xbb,
	0xaf, 0xcc, 0xf8, 0x31, 0x34, 0x42, 0xee, 0xeb, 0xcf, 0x98, 0x4b, 0xa9, 0x40, 0x72, 0x0e, 0xc3,
	0xb3, 0x88, 0xb9, 0x82, 0x6d, 0x7a, 0xed, 0x35, 0xf5, 0x9f, 0xc2, 0xa8, 0x78, 0xd6, 0xca, 0x92,
	0x46, 0xd0, 0x0c, 0xb9, 0xff, 0x34, 0x69, 0x9f, 0x36, 0x64, 0x2d, 0xbf, 0x84, 0xb3, 0x0f, 0x56,
	0x4b, 0xf1, 0xac, 0x3b, 0xd6, 0xf2, 0x3d, 0x0c, 0x1f, 0x31, 0x9f, 0x6d, 0x5e, 0x4b, 0xf9, 0x39,
	0x1c, 0xc2, 0xa8, 0x78, 0xc0, 0xaa, 0x02, 0xc8, 0x97, 0x50, 0x7f, 0xf6, 0x4a, 0xe2, 0x37, 0x6c,
	0x91, 0xe0, 0x37, 0x6c, 0x21, 0x0b, 0x7b, 0xe3, 0xfa, 0xf3, 0x84, 0x04, 0xda, 0x20, 0xf7, 0xa1,
	0xf5, 0xd8, 0xf3, 0x05, 0x8b, 0x24, 0x1f, 0xc2, 0x88, 0x5d, 0x7a, 0xef, 0x4c, 0x90, 0xb1, 0x70,
	0x0f, 0x2c, 0xe1, 0x5e, 0x99, 0xcf, 0x6d, 0xd1, 0x67, 0xaf, 0xc6, 0xd2, 0x26, 0x3e, 0x74, 0xce,
	0x78, 0x10, 0xb0, 0xa9, 0xe0, 0x11, 0x3a, 0xd0, 0x8e, 0x05, 0x8f, 0x5e, 0x66, 0x94, 0x4f, 0x6d,
	0xfc, 0x0c, 0x60, 0x32, 0x9f, 0xde, 0x30, 0xf1, 0x73, 0xc6, 0xc0, 0x1c, 0x82, 0x9f, 0x03, 0x4c,
	0x79, 0x10, 0x9c, 0xf1, 0xe0, 0xd2, 0xbb, 0xb2, 0xad, 0x2c, 0x4d, 0x0e, 0x26, 0xff, 0xd4, 0xa1,
	0x71, 0xe1, 0xbb, 0xc1, 0x46, 0xcc, 0x2e, 0x31, 0xd8, 0xaa, 0x32, 0x38, 0x91, 0xa7, 0x46, 0x4e,
	0x9e, 0x1c, 0x68, 0x87, 0xaa, 0xb7, 0x4f, 0x67, 0x8a, 0xd5, 0x9d, 0x71, 0x6a, 0xcb, 0x3b, 0xe8,
	0xb5, 0xba, 0x43, 0x4b, 0xdf, 0x21, 0x43, 0xf0, 0x1e, 0x40, 0xcc, 0xe7, 0xd1, 0x94, 0xc9, 0x96,
	0xd8, 0xdb, 0xea, 0x01, 0x01, 0x4d, 0xfb, 0x33, 0xce, 0xed, 0xe2, 0x01, 0xb4, 0x67, 0x2c, 0x16,
	0xca, 0xb3, 0x5d, 0xf1, 0x4c, 0xf7, 0x24, 0xcf, 0x2e, 0x3d, 0x5f, 0xd8, 0x1d, 0xf3, 0x1c, 0xf5,
	0x67, 0x1a, 0x2b, 0x10, 0x3f, 0x81, 0x0e, 0x7f, 0xc3, 0xa2, 0x5f, 0x23, 0x4f, 0x30, 0x1b, 0xf6,
	0xb7, 0x0e, 0xdb, 0xe3, 0x0c, 0x40, 0x02, 0xbb, 0x11, 0xbb, 0x75, 0xbd, 0xe0, 0x85, 0x4a, 0x6b,
	0xef, 0x28, 0x87, 0x02, 0x96, 0x93, 0xbf, 0xdd, 0xbc, 0xfc, 0x91, 0x9f, 0x60, 0x60, 0x58, 0xe7,
	0xbb, 0xc1, 0x26, 0x9c, 0x69, 0x84, 0xbe, 0x1b, 0x18, 0xd2, 0x34, 0xa9, 0x8a, 0x52, 0x10, 0x39,
	0x05, 0xcc, 0x9f, 0xb4, 0x92, 0x31, 0xf2, 0xe1, 0xf9, 0x6e, 0x90, 0x52, 0xc6, 0x58, 0xe4, 0x21,
	0x74, 0xa5, 0x02, 0x6e, 0x54, 0x46, 0x99, 0x2e, 0xa7, 0xd0, 0x4b, 0x63, 0xd7, 0x68, 0xe7, 0xca,
	0xda, 0x8f, 0xa0, 0xa7, 0xc4, 0x70, 0x93, 0xe4, 0xe4, 0x47, 0xe8, 0x67, 0xce, 0x6b, 0x74, 0xb3,
	0x29, 0x8f, 0x4e, 0x84, 0xd3, 0xa4, 0xd3, 0x98, 0xec, 0xba, 0xd1, 0x97, 0x0f, 0xd0, 0xf5, 0xfc,
	0x49, 0x77, 0xee, 0xfa, 0x09, 0x0c, 0x8c, 0xd0, 0xbc, 0x57, 0xe3, 0x0f, 0x00, 0xf3, 0xe1, 0x2b,
	0x55, 0xea, 0x21, 0x74, 0xc7, 0xf3, 0xe0, 0xfd, 0x72, 0x3c, 0x80, 0x5e, 0x1a, 0xbb, 0x4e, 0x87,
	0xaf, 0xf9, 0x24, 0xd3, 0x61, 0x65, 0x90, 0xbf, 0xeb, 0x60, 0x9d, 0xf3, 0xc9, 0x32, 0x19, 0x51,
	0x82, 0x50, 0x2f, 0x09, 0x82, 0xef, 0x06, 0x8a, 0xf2, 0x96, 0x11, 0x04, 0x63, 0xe7, 0xba, 0xd7,
	0xc8, 0x77, 0xaf, 0x2c, 0x3d, 0xcd, 0xaa, 0xf4, 0x1c, 0x40, 0x57, 0x8b, 0xc1, 0x73, 0x3e, 0x75,
	0x95, 0x93, 0x96, 0x93, 0x12, 0x2a, 0x39, 0x2c, 0xa5, 0x20, 0xf5, 0xda, 0x56, 0x5e, 0x05, 0x4c,
	0xca, 0xd2, 0x54, 0x31, 0xec, 0xa5, 0x77, 0xcb, 0x94, 0x98, 0x58, 0xe3, 0x1c, 0x22, 0x55, 0x22,
	0x16, 0x6e, 0x24, 0xd4, 0x76, 0x47, 0x6d, 0x67, 0x80, 0x6c, 0x38, 0x0b, 0x66, 0x6a, 0x0f, 0xd4,
	0x5e, 0x62, 0x16, 0xd5, 0x65, 0xe7, 0xbf, 0xd4, 0x65, 0xb7, 0xaa, 0x2e, 0xe4, 0x01, 0xfc, 0xef,
	0x09, 0x13, 0xe7, 0x7c, 0x72, 0xf7, 0xaf, 0xab, 0x69, 0xaf, 0x42, 0xd7, 0x3c, 0x5e, 0xeb, 0x9a,
	0x4f, 0xcc, 0xf3, 0x6f, 0x50, 0xe9, 0x2c, 0x01, 0x72, 0x0f, 0xba, 0x92, 0x89, 0x9b, 0xe4, 0x25,
	0x27, 0x9a, 0xe2, 0xeb, 0x13, 0xd9, 0xd0, 0xb8, 0xe6, 0x93, 0x84, 0xb3, 0x3a, 0x93, 0x42, 0x8e,
	0xff, 0x6a, 0x42, 0xfb, 0x91, 0x2b, 0xdc, 0xc7, 0x3e, 0x7f, 0x8b, 0xdf, 0x42, 0x27, 0x1d, 0xd6,
	0x70, 0x40, 0xcb, 0x63, 0x9f, 0x83, 0xb4, 0x32, 0xcb, 0x91, 0x1a, 0xde, 0x07, 0xc8, 0x26, 0x2e,
	0x44, 0x5a, 0x99, 0xd6, 0x9c, 0x21, 0xad, 0x8e, 0x64, 0xa4, 0x86, 0x27, 0xb0, 0x9b, 0x9f, 0x8c,
	0x70, 0x44, 0x97, 0x0c, 0x5d, 0xce, 0x1e, 0x5d, 0x36, 0x3e, 0xe9, 0xf0, 0xfc, 0x30, 0x83, 0x23,
	0xba, 0x64, 0x4e, 0x72, 0xf6, 0xe8, 0xb2, 0x89, 0x47, 0x87, 0xe7, 0x47, 0x11, 0x1c, 0xd1, 0x25,
	0xa3, 0x8d, 0xb3, 0x47, 0x97, 0xcd, 0x2b, 0xa4, 0x86, 0x14, 0xb6, 0x8d, 0x34, 0x63, 0x8f, 0x16,
	0x05, 0xde, 0xe9, 0xd3, 0x92, 0x6a, 0x93, 0x1a, 0x7e, 0x0d, 0xed, 0x44, 0x5d, 0xb1, 0x4f, 0x4b,
	0xaa, 0xec, 0x0c, 0x68, 0x59, 0x7a, 0x75, 0x63, 0xb3, 0x5f, 0x1e, 0x44, 0x5a, 0xf9, 0x41, 0x73,
	0x86, 0xb4, 0xfa, 0xd3, 0xa4, 0x03, 0x33, 0xf1, 0x44, 0xa4, 0x15, 0x4d, 0x76, 0x86, 0xb4, 0xaa,
	0xae, 0x3a, 0x30, 0x93, 0x3d, 0x44, 0x5a, 0x91, 0x50, 0x67, 0x48, 0xab, 0xba, 0x48, 0x6a, 0x78,
	0x04, 0x2d, 0xfd, 0xda, 0xb1, 0x4b, 0x0b, 0x8c, 0x71, 0x7a, 0xb4, 0x48, 0x03, 0xdd, 0x3a, 0xf3,
	0x64, 0xb1, 0x47, 0x8b, 0x0f, 0xdd, 0xe9, 0xd3, 0xd2, 0x6b, 0xd6, 0xfe, 0x46, 0x28, 0xb1, 0x47,
	0x8b, 0x72, 0xeb, 0xf4, 0x69, 0x49, 0x43, 0x49, 0x6d, 0xd2, 0x52, 0x7f, 0xe4, 0xbe, 0xf9, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x02, 0x16, 0x66, 0x43, 0xda, 0x0d, 0x00, 0x00,
}
